{{- include "ao-data-platform.backupValidate" . -}}
{{- if .Values.clickhouse.backup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.clickhouse.backup.serviceAccount.name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.clickhouse.backup.aws.roleArn | quote }}
  labels:
    {{- include "ao-data-platform.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ao-data-platform.chiName" . }}-backup-job
  labels:
    {{- include "ao-data-platform.labels" . | nindent 4 }}
{{- end }}
