{{- include "ao-data-platform.backupValidate" . -}}
{{- if .Values.clickhouse.backup.enabled }}
{{- $b := .Values.clickhouse.backup }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $b.secret }}
  labels:
    {{- include "ao-data-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ $b.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ required "clickhouse.backup.externalSecret.secretStoreRef.name is required." $b.externalSecret.secretStoreRef.name }}
    kind: {{ $b.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ $b.secret }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: {{ "{{ .password }}" | quote }}
        config.yml: |
          {{- include "ao-data-platform.backupConfig" . | nindent 10 }}
  data:
    - secretKey: password
      remoteRef:
        {{- include "ao-data-platform.externalSecretRemoteRef" (dict "key" $b.externalSecret.remoteRef.key "remoteRef" $b.externalSecret.remoteRef "errorContext" "for the backup user") | nindent 8 }}
{{- end }}
