apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-schema
  labels:
    {{- include "ao-data-platform.labels" . | nindent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "sql/*.sql" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
