-- Support newer OTel GenAI semantic conventions (OpenLLMetry v0.55.0+ /
-- OTel-official instrumentors, e.g. Google ADK) on spans_normalized_mv.
--
-- SUPERSEDED, AND DELIBERATELY INERT. The SELECT this file used to install was
-- carried forward by 0020_spans_normalized_mv_tool_call_response.sql and now
-- lives in 0021_spans_normalized_mv_planning_tool_fallbacks.sql, the last
-- writer of this view. The statement was removed from here rather than left in
-- place because schema-job.yaml re-runs every /sql/*.sql on install AND upgrade
-- with no ledger or checksum: a superseded ALTER ... MODIFY QUERY is not merely
-- redundant, it is a transient REGRESSION. Re-running this file restored the
-- pre-tool_call_response SELECT for the window between it and 0020, and because
-- the view is insert-triggered and forward-only, any span ingested in that
-- window keeps a blank tool result permanently -- the exact defect 0020 fixes.
-- Measured on a two-replica cluster: the view lost, then regained, the
-- tool_call_response handling on every upgrade pass.
--
-- The file is retained (not deleted) to hold the numbering, so this ordinal is
-- never reused and the chart's history stays readable. Retaining it costs
-- nothing: the schema Job pipes a comment-only file to clickhouse-client, which
-- is a no-op.
--
-- Under this chart's execution model sql/ is a DESIRED-STATE script set, not a
-- migration history -- so exactly one file may carry the current definition of a
-- given view. That is 0006 (CREATE ... IF NOT EXISTS, which owns the view on a
-- fresh install) plus one trailing ALTER for clusters where the CREATE is a
-- no-op. Verified by execution: with this file inert, the resulting view is
-- byte-identical to the previous file set on a fresh install AND on an upgrade
-- from the previously released chart, with the DEFINER pinned by 0014 preserved.
-- Note this differs from the monolith test fixture, where the equivalent file
-- CANNOT be edited: clickhouse-migrations md5-checksums applied files and raises
-- on any change to one already applied. That directory is append-only by
-- construction; this one is not. Files correspond to that fixture by basename,
-- not ordinal (this chart carries migrations the fixture lacks, so ordinals
-- drift: this file is the fixture's 0012); what holding ordinals preserves is
-- the mirrored files' relative order. Only the redundant statement is gone.
--
-- What that superseded SELECT added, kept here as the record of why the change
-- was made (all of it now carried by 0021):
--   1. Content: the new semconv moved prompt/completion content from per-attribute
--      indexed keys (gen_ai.prompt.{N}.content) to single JSON-array attributes
--      gen_ai.input.messages / gen_ai.output.messages, each an array of
--      {role, parts:[{type, content} | {type:'tool_call', id, name, arguments}]},
--      with a message-level `content` fallback for emitters that omit `parts`.
--   2. Grouping: gen_ai.conversation.id (the OTel-standard conversation key) is
--      appended to the conversation_id coalesce (vendor keys stay first for
--      back-compat), so standard/ADK agents that set only the standard key group
--      into conversations.
--
-- Both axes are total / null-safe -- every expression degrades to '' for a
-- missing or malformed JSON path and never raises, so a source INSERT into
-- otel_traces can never be failed by this view (a raising MV halts ingestion
-- cluster-wide). 0021 preserves that property.
