-- Extract Cortex planning tool-use output as the completion.
--
-- SUPERSEDED BY 0026, AND DELIBERATELY INERT. The SELECT this file used to
-- install now lives in 0026_spans_normalized_mv_planning_tool_calls.sql,
-- which is the last writer of this view. The statement was removed from
-- here rather than left in place because schema-job.yaml re-runs every
-- /sql/*.sql on install AND upgrade with no ledger or checksum: a
-- superseded ALTER ... MODIFY QUERY is not merely redundant, it is a
-- transient REGRESSION. Left in place, this file would restore the
-- pre-planning-tool-calls SELECT for the window between it and 0026, and
-- because the view is insert-triggered and forward-only, a Cortex planning
-- tool-use span ingested in that window keeps the superseded rendering
-- permanently. Measured on a two-replica cluster: the equivalent flip-flop
-- when 0020 was superseded by this file.
--
-- The file is retained (not deleted) to hold the numbering, so this ordinal
-- is never reused, the relative order of files mirrored from the source
-- schema set is preserved, and the chart's history stays readable.
-- Retaining it costs nothing: the schema Job pipes a comment-only file to
-- clickhouse-client, which is a no-op.
--
-- Under this chart's execution model sql/ is a DESIRED-STATE script set, not
-- a migration history -- so exactly one file may carry the current
-- definition of a given view. That is 0006 (CREATE ... IF NOT EXISTS, which
-- owns the view on a fresh install) plus one trailing ALTER for clusters
-- where the CREATE is a no-op -- now 0026.
--
-- What that superseded SELECT added, kept here as the record of why the
-- change was made (superseded again by 0026):
--   1. Changed the completion extraction (idx=0 Snowflake-native arm) to a
--      seven-arm COALESCE: record_root.output -> planning.thinking_response
--      -> planning.response -> planning.tool_execution.results ->
--      planning.tool_selection.name -> tool.cortex_search.results ->
--      tool.cortex_analyst.text, with the matching _completion_indices
--      discovery arm checking the same seven attributes.
--   2. Swapped thinking_response ahead of response (0006..0020 had them
--      reversed), matching the read query's preference for the
--      extended-thinking chain-of-thought over the formal output.
--   3. The last two arms (agent.tool.cortex_search.results,
--      agent.tool.cortex_analyst.text) were an MV-only fold of the tool
--      namespace, deliberately absent from the read query.
--
-- SIZE (historical): tool_execution.results was tool-controlled and copied
-- verbatim, so completions[].message was unbounded here too. 0026 drops that
-- arm from the completion text (tool_execution.results is the turn's
-- cumulative input, not this step's output) in favor of a structured
-- tool_calls arm.
--
-- Every expression it added was total (never raises), preserving this
-- view's headline invariant: a raising SELECT expression fails the source
-- INSERT into otel_traces and silently HALTS span ingestion cluster-wide.
-- 0026 preserves that property.
