-- Per-agent completeness watermark for the conversation turn rollup writer
-- (the job that loads ADK/gen_ai conversations into conversations_normalized,
-- which the 0012 MV's Traceloop-only gate cannot serve). After each run's
-- INSERT lands, the writer publishes one row per scanned service_name: every
-- turn whose spans arrived at or before `watermark` has been written. The
-- cursor cannot be derived from the target table — it is arrival-ordered, so
-- max(turn_start) over written rows is not a completeness bound — which is
-- why it is published rather than computed. Keyed by service_name, the
-- writer's scan unit; spans_normalized has no account column and no agent
-- identifier (0 of 5.6M prod-us1 spans over 7 days carry
-- montecarlo.agent_mcon, measured 2026-08-28), so nothing finer exists to
-- key on, and two agents sharing one service_name share one cursor.
--
-- Current-state metadata, not time-series (the 0017 llm_worker_info shape):
-- no TTL and no PARTITION BY. A watermark must survive ANY pause — a writer
-- stopped for longer than a retention window must still hold its last cursor,
-- and no row then unambiguously means never published.
--
-- ReplicatedReplacingMergeTree(watermark): the watermark VALUE is the version,
-- so a merge keeps the highest watermark per service_name and a regressed
-- re-publish (a retry or backfill carrying a lower cursor) is discarded by
-- the engine — monotonicity is structural, not a read-side convention. Read
-- idiom: SELECT service_name, max(watermark) ... GROUP BY service_name. The
-- max is the same answer before and after merges, so reads need no ORDER BY /
-- LIMIT 1 BY and no FINAL. `published_at` is liveness and provenance only —
-- read max(published_at) for "is the writer alive?". A merge keeps only the
-- highest-watermark row, so a regressed re-publish's later publish time
-- disappears with its row; same-watermark republish ties resolve last-wins,
-- so an idle writer's fresh published_at survives a merge (pinned by test
-- on the monolith mirror). Both are immaterial at run-interval scale. The
-- same rule makes an
-- over-advanced cursor unfixable by re-publish: a lower watermark loses
-- both the max() read and the merge by design, so correcting one is an
-- operator action (delete the service_name's rows), not a writer action. A
-- service_name retired and later reused inherits the retired agent's cursor,
-- which over-asserts the new agent's completeness; until corrected, every
-- publish regresses, so max(published_at) reads stale while the writer is
-- healthy.
--
-- `published_at` defaults to now64(9) because it carries a liveness read: a
-- writer that omitted the column would otherwise record the epoch, which reads
-- as a writer that has never run rather than as one that just ran. The default
-- is evaluated once per inserted block, so one batched publish shares one
-- timestamp. It binds at CREATE: an install already holding this table keeps
-- the old column, and only an explicit MODIFY COLUMN would add the default
-- there.
-- `watermark` takes no default by design — it is an event-time bound the
-- writer is expected to state, and no wall-clock fallback could be correct,
-- because it would assert completeness the run never earned. Nothing enforces
-- that: an INSERT naming only service_name stores the epoch. That direction is
-- fail-safe, since an epoch cursor loses every merge and every max().
--
-- `watermark` is an EVENT-TIME bound (comparable to turn_start / period_to)
-- whose advancement the writer gates on arrival completeness; the arrival
-- signal itself is the writer's choice (a MATERIALIZED now() column vs
-- system.parts), not this table's concern. One BATCHED INSERT per run covers
-- every scanned service_name — per-service inserts would create a part per
-- row on a high-frequency job. Async replica lag can only under-assert
-- completeness (a replica that has not seen the latest row answers with a
-- lower watermark), which is the fail-safe direction; reads of this table need
-- no select_sequential_consistency.
--
-- That covers the cursor read alone. A consumer reads the cursor here and then
-- reads turns from conversations_normalized — two independently replicated
-- tables, each with its own queue, so the writer ordering its own inserts binds
-- only the replica it wrote to. On a follower the watermark can be current
-- while the turns it covers are not yet visible, which over-asserts
-- completeness. A consumer joining the two owes that read a pinned replica or
-- select_sequential_consistency on the data side.
--
-- The writer runs as `monte_carlo`; the INSERT grant ships in this release
-- (templates/clickhouse-installation.yaml). Files correspond to the monolith
-- test fixture by basename, not ordinal (see 0019's note); the fixture's
-- version of this table is a plain ReplacingMergeTree with no ON CLUSTER —
-- intentional, it runs on a single-node test container.
CREATE TABLE IF NOT EXISTS otel_traces.conversation_rollup_watermarks ON CLUSTER '{cluster}'
(
    `service_name` LowCardinality(String),
    `watermark` DateTime64(9),
    `published_at` DateTime64(9) DEFAULT now64(9)
)
ENGINE = ReplicatedReplacingMergeTree(watermark)
ORDER BY service_name;
